# Generated by Django 5.2 on 2025-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusigntoken',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='docusigntoken',
            name='base_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
