# Generated by Django 5.2 on 2025-07-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0003_docusigntoken_account_id_docusigntoken_base_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusigntoken',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='docusigntoken',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
