# Generated by Django 5.2 on 2025-07-29 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_customuser_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
