# Generated by Django 5.2 on 2025-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_alter_customuser_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
