# Generated by Django 5.2 on 2025-07-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_customuser_reset_password_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlock_account_token',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
