# Generated by Django 5.2 on 2025-07-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_customuser_unlock_account_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unlock_account_token_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unlock_account_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
