# Generated by Django 5.2 on 2025-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_customuser_unlock_account_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
