# Generated by Django 5.2 on 2025-06-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
                ('Signer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BinaryField(default=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('People', models.IntegerField(null=True)),
                ('Completed_Value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Paid', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/contracts')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company')),
                ('client_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Selected_VAT_Rate', models.IntegerField(null=True)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.contract')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Template_first_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Template_first_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Template_second_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Email_Template_second_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_invoices', models.IntegerField()),
                ('schedule', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('reminders_count', models.IntegerField()),
                ('reminders_per', models.CharField(max_length=255)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total_VAT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total_with_VAT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('billed_to_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company')),
                ('billed_to_individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.contract')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(null=True)),
                ('status', models.CharField()),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corresponds_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.contractitem')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='JobAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.job')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Represents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_object_id', models.PositiveIntegerField(null=True)),
                ('to_object_id', models.PositiveIntegerField(null=True)),
                ('primary_contact', models.BooleanField(default=True)),
                ('from_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='represents_from_type', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='represents_to_type', to='contenttypes.contenttype')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedContractWordDocumentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/company')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedContractWordDocumentIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/individual')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
