# Generated by Django 5.2 on 2025-06-26 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual'),
        ),
    ]
