# Generated by Django 5.2 on 2025-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_contract_client_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractitem',
            name='Selected_VAT_Rate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
