# Generated by Django 5.2 on 2025-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_contractitem_selected_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_summary',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
