# Generated by Django 5.2 on 2025-06-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_initial'),
        ('MainApp', '0005_alter_invoice_summary_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace'),
        ),
        migrations.AddField(
            model_name='jobassigned',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace'),
        ),
    ]
