# Generated by Django 5.2 on 2025-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_invoiceitem_workplace_jobassigned_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
