# Generated by Django 5.2 on 2025-06-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Deadline',
            field=models.DateField(null=True),
        ),
    ]
