# Generated by Django 5.2 on 2025-06-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_initial'),
        ('MainApp', '0008_alter_job_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('Paid', models.BooleanField(default=False)),
                ('invoice_file', models.FileField(null=True, upload_to='documents/invoices')),
                ('InvoiceSummary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.contract')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesToInvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoiceitem')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='InvoiceItems',
            field=models.ManyToManyField(through='MainApp.InvoicesToInvoiceItems', to='MainApp.invoiceitem'),
        ),
    ]
