# Generated by Django 5.2 on 2025-06-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_invoice_invoicestoinvoiceitems_invoice_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual'),
        ),
    ]
