# Generated by Django 5.2 on 2025-06-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_invoice_client_company_invoice_client_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_summary',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.contract'),
        ),
    ]
