# Generated by Django 5.2 on 2025-06-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_invoice_summary_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='corresponds_to',
        ),
        migrations.AddField(
            model_name='job',
            name='corresponds_to_ContractItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.contractitem'),
        ),
        migrations.AddField(
            model_name='job',
            name='corresponds_to_InvoiceItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoiceitem'),
        ),
    ]
