# Generated by Django 5.2 on 2025-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_remove_job_corresponds_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Completed_Value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
