# Generated by Django 5.2 on 2025-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_invoice_completed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Completed_Value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Completed_Value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
