# Generated by Django 5.2 on 2025-07-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_alter_contract_completed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
