# Generated by Django 5.2 on 2025-07-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_initial'),
        ('MainApp', '0016_remove_email_template_first_individual_workplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInvoiceOnlyOneWithContract_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailInvoiceOnlyOneWithContract_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
