# Generated by Django 5.2 on 2025-07-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_initial'),
        ('MainApp', '0017_emailinvoiceonlyonewithcontract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcontractworddocumentcompany',
            name='file',
            field=models.FileField(upload_to='documents/contract/company'),
        ),
        migrations.AlterField(
            model_name='uploadedcontractworddocumentindividual',
            name='file',
            field=models.FileField(upload_to='documents/contract/individual'),
        ),
        migrations.CreateModel(
            name='UploadedInvoiceWordDocumentCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/invoice/company')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedInvoiceWordDocumentIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/invoice/individual')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
