# Generated by Django 5.2 on 2025-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_alter_uploadedcontractworddocumentcompany_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signingUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
