# Generated by Django 5.2 on 2025-07-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_contract_signingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Signed',
            field=models.BooleanField(default=False),
        ),
    ]
