# Generated by Django 5.2 on 2025-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
