# Generated by Django 5.2 on 2025-07-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_docusigntoken_user_email_and_more'),
        ('MainApp', '0021_contract_envelope_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubjectforDocuSign_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubjectforDocuSign_individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
        ),
    ]
