# Generated by Django 5.2 on 2025-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_emailsubjectfordocusign_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_summary',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_summary',
            name='reminders_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice_summary',
            name='reminders_per',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_summary',
            name='schedule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
