# Generated by Django 5.2 on 2025-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_alter_invoice_summary_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_summary',
            name='last_invoice_Total_VAT',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='last_invoice_Total_with_VAT',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='last_invoice_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
