# Generated by Django 5.2 on 2025-07-15 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_invoice_summary_last_invoice_total_vat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeBccd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsCompaniesToBeBccd', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeCCd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsCompaniesToBeCCd', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeTod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsCompaniesToBeTod', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeBccd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsIndividualsToBeBccd', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeCCd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsIndividualsToBeCCd', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeTod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactsIndividualsToBeTod', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeBccd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersToBeBccd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeCCd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersToBeCCd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeTod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersToBeTod', to=settings.AUTH_USER_MODEL),
        ),
    ]
