# Generated by Django 5.2 on 2025-07-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_docusigntoken_user_email_and_more'),
        ('MainApp', '0025_invoice_summary_contactscompaniestobebccd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThroughEmailsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeBccd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeCCd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeTod',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeBccd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeCCd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeTod',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='UsersToBeBccd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='UsersToBeCCd',
        ),
        migrations.RemoveField(
            model_name='invoice_summary',
            name='UsersToBeTod',
        ),
        migrations.CreateModel(
            name='ContactsCompaniesToBeBccdThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsCompaniesToBeCCdThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsCompaniesToBeTodThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_company')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsIndividualsToBeBccdThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsIndividualsToBeCCdThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsIndividualsToBeTodThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual')),
                ('invoice_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersToBeBccdThrough',
            fields=[
                ('throughemailsusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.throughemailsusers')),
            ],
            bases=('MainApp.throughemailsusers',),
        ),
        migrations.CreateModel(
            name='UsersToBeCCdThrough',
            fields=[
                ('throughemailsusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.throughemailsusers')),
            ],
            bases=('MainApp.throughemailsusers',),
        ),
        migrations.CreateModel(
            name='UsersToBeTodThrough',
            fields=[
                ('throughemailsusers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.throughemailsusers')),
            ],
            bases=('MainApp.throughemailsusers',),
        ),
        migrations.AddField(
            model_name='throughemailsusers',
            name='invoice_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.invoice_summary'),
        ),
        migrations.AddField(
            model_name='throughemailsusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='throughemailsusers',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.workplace'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeBccd',
            field=models.ManyToManyField(related_name='ContactsCompaniesToBeBccd', through='MainApp.ContactsCompaniesToBeBccdThrough', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeCCd',
            field=models.ManyToManyField(related_name='ContactsCompaniesToBeCCd', through='MainApp.ContactsCompaniesToBeCCdThrough', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsCompaniesToBeTod',
            field=models.ManyToManyField(related_name='ContactsCompaniesToBeTod', through='MainApp.ContactsCompaniesToBeTodThrough', to='MainApp.client_company'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeBccd',
            field=models.ManyToManyField(related_name='ContactsIndividualsToBeBccd', through='MainApp.ContactsIndividualsToBeBccdThrough', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeCCd',
            field=models.ManyToManyField(related_name='ContactsIndividualsToBeCCd', through='MainApp.ContactsIndividualsToBeCCdThrough', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='ContactsIndividualsToBeTod',
            field=models.ManyToManyField(related_name='ContactsIndividualsToBeTod', through='MainApp.ContactsIndividualsToBeTodThrough', to='MainApp.client_individual'),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeBccd',
            field=models.ManyToManyField(related_name='UsersToBeBccd', through='MainApp.UsersToBeBccdThrough', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeCCd',
            field=models.ManyToManyField(related_name='UsersToBeCCd', through='MainApp.UsersToBeCCdThrough', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='UsersToBeTod',
            field=models.ManyToManyField(related_name='UsersToBeTod', through='MainApp.UsersToBeTodThrough', to=settings.AUTH_USER_MODEL),
        ),
    ]
