# Generated by Django 5.2 on 2025-07-16 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_throughemailsusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_summary',
            name='current_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
