# Generated by Django 5.2 on 2025-07-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_invoice_summary_current_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_summary',
            old_name='current_time',
            new_name='creates_at',
        ),
    ]
