# Generated by Django 5.2 on 2025-07-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_rename_current_time_invoice_summary_creates_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_summary',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
