# Generated by Django 5.2 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_rename_creates_at_invoice_summary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='represents',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
