# Generated by Django 5.2 on 2025-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_represents_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='started_at',
            field=models.DateField(null=True),
        ),
    ]
