# Generated by Django 5.2 on 2025-07-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_alter_job_completed_at_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
