# Generated by Django 5.2 on 2025-07-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_alter_job_completed_at_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_company',
            name='Signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.client_individual'),
        ),
    ]
