# Generated by Django 5.2 on 2025-07-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_alter_client_company_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_summary',
            name='MainClientToBeBccd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='MainClientToBeCCd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice_summary',
            name='MainClientToBeTod',
            field=models.BooleanField(default=False),
        ),
    ]
