# Generated by Django 5.2 on 2025-08-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_invoice_summary_mainclienttobebccd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceSummary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.invoice_summary'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.contract'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.invoice_summary'),
        ),
    ]
