# Generated by Django 5.2 on 2025-08-13 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0035_alter_invoice_invoicesummary_alter_invoice_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_summary',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.contract'),
        ),
    ]
